### ISSUE TITLE
Request: Telegram

### ISSUE THREAD

**Issue by Muetze42** [kevincobain2000/laravel-alert-notifications#15]
Would it be possible to include a telegram notification in the package?

Example Package:
[Telegram Notifications Channel for Laravel](https://github.com/laravel-notification-channels/telegram)

**Comment by kevincobain2000** [comment]
A simple ``->content()`` implementation can be added without much effort. Although, [Telegram](https://github.com/laravel-notification-channels/telegram) doesn't seem to support a proxy. Laravel users would need to add custom Guzzle Client to their apps. https://github.com/php-telegram-bot/core/issues/667#issuecomment-334851805

We can consider making ``shouldAlert()`` method public, which checks the config and throttles the exception passed.
